# Generated by Django 4.0.5 on 2022-06-03 10:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('company_id', models.AutoField(primary_key=True, serialize=False)),
                ('is_kyb_done', models.BooleanField()),
                ('is_kyc_done', models.BooleanField()),
                ('is_buyer', models.BooleanField()),
                ('is_seller', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Business_Details',
            fields=[
                ('company', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='kyb.company')),
                ('GSTIN', models.CharField(max_length=50, null=True)),
                ('PAN', models.CharField(blank=True, max_length=200, null=True)),
                ('CIN', models.CharField(max_length=200, null=True)),
            ],
        ),
    ]
