# Generated by Django 4.0.5 on 2022-06-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyb', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Business_Details',
            new_name='BusinessDetail',
        ),
        migrations.AddField(
            model_name='company',
            name='company_name',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
