# Generated by Django 4.0.5 on 2022-06-03 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyb', '0004_rename_customer_profile_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='is_buyer',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_kyb_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_kyc_done',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='company',
            name='is_seller',
            field=models.BooleanField(default=False),
        ),
    ]
