# Generated by Django 4.0.5 on 2022-06-06 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyb', '0006_bankdetail_customer_businessdetail_tan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='businessdetail',
            name='DIN',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
