# Generated by Django 4.0.5 on 2022-06-07 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyb', '0008_profile_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='businessdetail',
            name='annual_revenue',
        ),
        migrations.RemoveField(
            model_name='businessdetail',
            name='industry',
        ),
        migrations.RemoveField(
            model_name='businessdetail',
            name='phone_number',
        ),
        migrations.AlterField(
            model_name='profile',
            name='annual_revenue',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=122),
        ),
    ]
