# Generated by Django 4.0.5 on 2022-06-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyb', '0010_rename_company_address_businessdetail_company_registered_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetail',
            name='account_no',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='bank_name',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='branch_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetail',
            name='ifsc_code',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
