# Generated by Django 4.0.5 on 2022-06-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyb', '0011_alter_bankdetail_account_no_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyb.company', unique=True),
        ),
    ]
