# Generated by Django 4.0.5 on 2022-06-10 10:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kyb', '0013_alter_profile_company'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='invitetobuyer',
            name='company',
        ),
        migrations.RemoveField(
            model_name='invitetobuyer',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='product',
            name='company',
        ),
        migrations.RemoveField(
            model_name='subsription',
            name='product',
        ),
        migrations.DeleteModel(
            name='Customer',
        ),
        migrations.DeleteModel(
            name='InviteToBuyer',
        ),
        migrations.DeleteModel(
            name='Product',
        ),
        migrations.DeleteModel(
            name='Subsription',
        ),
    ]
