# Generated by Django 4.0.5 on 2022-07-06 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kyb', '0015_company_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='admin_id',
            field=models.EmailField(max_length=200, null=True),
        ),
    ]
