# Generated by Django 4.0.5 on 2022-06-10 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='product_detail',
            new_name='product_details',
        ),
    ]
