# Generated by Django 4.0.5 on 2022-06-11 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0002_rename_product_detail_product_product_details'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tiers',
            field=models.JSONField(null=True),
        ),
    ]
