# Generated by Django 4.0.5 on 2022-06-12 04:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sellers', '0003_product_tiers'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='tiers',
        ),
    ]
