# Generated by Django 4.0.5 on 2022-07-08 01:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kyb', '0016_company_admin_id'),
        ('sellers', '0006_remove_customer_company_name_customer_domain_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customer',
            old_name='user',
            new_name='buyer',
        ),
        migrations.AddField(
            model_name='customer',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='kyb.company'),
        ),
    ]
