# Generated by Django 4.0.5 on 2022-06-05 09:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_user_options_user_date_joined_user_first_name_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
